"""UI 字串。英文為預設；zh 必須與 en 同 key。程式碼裡不得出現寫死的句子。"""
STRINGS = {
    "en": {
        "html_lang": "en", "doc_title": "BU10 Portfolio Review {ym}",
        "h1": "BU10 Portfolio Review",
        "intro": "Monthly. Exceptions first, evidence after. Manpower comes from the EIS control lists, schedules from the PM biweekly briefing.",
        "tb_report": "Report month", "tb_data": "Manpower data", "tb_data_v": "{start} to {end}, {n} projects",
        "tb_snap": "Briefing snapshot", "tb_snap_v": "{date} (revision {rev})", "tb_gen": "Generated", "tb_gen_v": "{date}, pipeline v{ver}",
        "s_decisions": "Decisions this month", "s_decisions_lead": "Ranked by urgency. Each item carries its evidence and its source. Orange appears only here and on fields that need a decision.",
        "decision_needed": "Decision needed:", "source": "Source:", "none": "none",
        "ex_milestones_passed_title": "{n} milestones passed without a stage change",
        "ex_milestones_passed_ask": "Ask the PMs to update the stage or explain the delay.",
        "ex_suspended_charging_title": "{suspended} suspended of {briefed} briefed, {charging} still charging manpower, {twins} booked under a second code",
        "ex_suspended_charging_ask": "Terminated projects should carry no manpower; decide where any remaining FTE moves. Confirm whether suspended projects resume or close, and merge any second identity into one project code.",
        "ex_susp_twin_h": "Second identity, likely the same project under another code",
        "ex_susp_twin_line": "{name} ({code}) is {cat} in the briefing, but {twin} ({twin_code}) still books {fte} FTE in {mon}{cl}",
        "ex_susp_twin_cl": " and has its own control list",
        "cat_terminated": "terminated", "cat_suspended": "suspended", "cat_inactive": "inactive",
        # 2026-10-01 之前 ingest 的快照（extra 無 terminated/suspended/briefed）
        "ex_suspended_charging_legacy_title": "{n} inactive (snapshot predates the terminated/suspended split), {charging} still charging manpower, {twins} booked under a second code",
        "ex_suspended_charging_legacy_ask": "Terminated projects should carry no manpower; decide where any remaining FTE moves. Confirm whether suspended projects resume or close, and merge any second identity into one project code. Re-run ingest_month for this month to get the terminated / suspended split.",
        "ex_susp_charging_h": "Still charging in {mon}",
        "ex_susp_wound_susp_h": "Suspended but no manpower since {since}: will it resume?",
        "ex_susp_wound_line": "{name}: peak {peak} FTE in {peak_month}, zero since {zero_since}",
        "ex_susp_zero_h": "Suspended with no manpower all year ({n})",
        "ex_budget_missing_title": "{n} control lists have no budget plan; the Q4 forecast covers {covered} projects",
        "ex_budget_missing_ask": "Require the PMs to fill in budgets, otherwise the Q4 capacity discussion has no basis.",
        "ex_mp_slipped_title": "{n} projects moved MP more than {days} days past the original date",
        "ex_mp_slipped_ask": "Confirm the new dates.",
        "ex_spare_capacity_title": "{n} departments are below {pct}% load, the only spare capacity left",
        "ex_spare_capacity_ask": "The other {full} departments sit at 100%; the reporting mechanism cannot show overload.",
        "src_briefing": "Briefing {date}", "src_briefing_summary": "Briefing stage column; Resource Summary; Control List",
        "src_control_list_pva": "Control List, Plan vs Actual sheet", "src_briefing_mp": "Briefing MP Date vs Original MP Date",
        "src_control_list_month": "Control List monthly sheets, allocated FTE over keyed-in headcount",
        "stage_rfq": "RFQ / RFI", "stage_poc": "POC", "stage_exec": "Execution", "stage_mp": "MP", "stage_sustain": "Sustain / EOP",
        "stage_terminated": "Terminated", "stage_suspended": "Suspended", "stage_fte": "Total FTE, {mon} (incl. FU)",
        "s_upcoming": "Milestones, next {weeks} weeks", "s_upcoming_lead": "Including those due in the past 7 days.",
        "col_date": "Date", "col_project": "Project", "col_customer": "Customer", "col_milestone": "Milestone", "col_stage": "Stage",
        "passed": "passed",
        "s_timeline": "Six-month timeline", "s_timeline_lead": "Weekly grid. Projects with a milestone in the window, or RFQ / RFI without dates. Terminated and suspended projects are not listed.",
        "no_dates": "{stage}, no dates yet", "legend_marks": "EVT (open square)  DVT (square)  PVT (triangle)  MP (circle)",
        "legend_late": "passed without a stage change", "legend_today": "dashed line = today",
        "s_capacity": "Manpower and capacity", "s_capacity_lead": "One chart, three facts: keyed-in BU headcount is the ceiling, actual manpower already runs along it, and the September to December budget covers only part of the portfolio.",
        "cap_budget_note": "Budget covers {covered} / {total} projects, BU RD + PM only", "lg_capacity": "BU keyed-in headcount (ceiling)",
        "lg_capacity_note": "later months carried from {mon}",
        "lg_actual": "BU RD + PM actual", "lg_budget": "BU RD + PM budget (dashed)", "lg_fu": "FU RD actual",
        "lg_actual_planned": "BU RD + PM actual, same projects as the budget (thin dotted)",
        "lbl_ceiling": "Ceiling", "lbl_actual": "BU actual", "lbl_budget": "Budget", "lbl_fu": "FU actual",
        "lbl_actual_planned": "Same {n} projects actual",
        "s_health": "Data health", "s_health_lead": "Every row affects how far the charts above can be trusted. Decide means the BU head has to act; track is handled by the report owner.",
        "col_level": "Level", "col_check": "Check", "col_count": "Count", "col_projects": "Projects", "col_source": "Source",
        "lv_decide": "decide", "lv_track": "track", "lv_ok": "ok",
        "hc_budget_missing": "Control list without a budget plan", "hc_milestones_passed": "Milestone passed, stage not advanced",
        "hc_suspended_second_identity": "Suspended project booked under a second code",
        "hc_in_briefing_no_cl": "In the briefing (not terminated or suspended) but no control list", "hc_in_cl_no_briefing": "Control list exists but not in the briefing",
        "hc_mp_slipped": "MP moved more than 60 days past the original date", "hc_mp_typo": "MP more than 300 days from the original date", "hc_customer_blank": "Customer is NA, TBD or blank",
        "hc_name_unresolved": "Name could not be matched to a project code", "hc_task_description_blank": "BU tasks reported without a description (months)",
        "hc_briefing_stale": "Briefing row not updated for more than 60 days", "hc_cl_unreadable": "Control list file could not be read",
        "hc_cl_format_drift": "Control list sheet or column missing", "hc_duplicate_source": "Several source rows resolved to one project code",
        "hc_dept_denominator_inconsistent": "Keyed-in headcount differs across files",
        "hc_dept_function_inconsistent": "Department function differs across files",
        "hc_cross_month_correction": "Past-month figures changed since last report", "hc_names_masked": "Person names masked in task text",
        "hs_control_list": "Control List", "hs_briefing": "Briefing", "hs_cross": "Cross-check", "hs_snapshot": "Previous snapshot",
        "s_appendix": "Project appendix", "s_appendix_lead": "Pick a project. Task lists are collapsed by default.",
        "ms_kickoff": "Kick-off", "ms_evt": "EVT", "ms_dvt": "DVT", "ms_pvt": "PVT", "ms_mp": "MP",
        "days_ahead": "in {d} days", "days_ago": "{d} days ago", "not_filled": "not filled", "not_in_briefing": "not in briefing",
        "pva_line": "budget {plan}{missing}, actual through {mon} {actual}", "pva_missing": " (not filled)",
        "no_control_list": "This project has no control list.", "s_tasks": "Task list",
        "task_summary": "{mon}: {bu} BU tasks, {fu} FU tasks, {fte} FTE", "col_side": "Side", "col_function": "Function", "col_dept": "Department", "col_fte": "FTE", "col_task": "Task",
        "expand": "expand", "collapse": "collapse",
        "foot_1": "FTE per person is capped at 1.0 by the reporting form, so overload cannot appear in these numbers.",
        "foot_2": "Department load uses keyed-in headcount as the denominator, not the official headcount.",
        "foot_3": "Budget coverage is stated wherever budget figures are used.",
        "v_menu": "Menu", "v_nav_overview": "Overview", "v_nav_decisions": "Decisions", "v_nav_health": "Data health", "v_nav_appendix": "Project appendix",
        "v_total": "Total", "v_kpi_total": "Total projects", "v_kpi_total_sub": "{briefed} in Briefing, {inactive} terminated or suspended",
        "v_kpi_rfq": "RFQ / RFI", "v_kpi_poc": "POC", "v_kpi_exec": "Execution", "v_kpi_mp": "MP + Sustain", "v_kpi_mp_sub": "{mp} MP, {sustain} sustain / EOP",
        "v_kpi_risk": "At risk", "v_kpi_risk_sub": "Milestone passed, or MP slipped over {days} days",
        "v_c_stage": "Projects by stage", "v_c_customer": "Projects by customer", "v_c_gantt": "Timeline, next {months} months",
        "v_c_heat": "Resource load by function", "v_c_heat_dept": "Resource load by department", "v_c_forecast": "BU RD + PM: actual vs headcount",
        "v_c_milestones": "Milestones, next {weeks} weeks",
        "v_cat_not_in_briefing": "Not in Briefing", "v_cat_blank": "(blank)", "v_cat_others": "Others", "v_no_data": "no data",
        "v_heat_note": "Load = allocated FTE / people who keyed in, not headcount. Grey cells: nobody keyed in.",
        "v_gantt_note": "Red marks a milestone that passed without a stage change. Terminated and suspended projects are not listed.",
        "v_today": "Today", "v_lg_cap": "Keyed-in BU headcount", "v_lg_cap_carried": "Headcount, assumed same as {mon}",
        "v_lg_actual": "Actual, BU RD + PM", "v_lg_plan": "Budget plan, BU RD + PM", "v_lg_fu": "Actual, FU RD",
        "v_lg_pva_actual": "Actual", "v_lg_pva_plan": "Plan", "v_pva_no_plan": "No budget plan for this group.",
        "v_st_passed": "Passed", "v_st_due": "Due soon", "v_st_ok": "Upcoming",
        "v_col_projects": "Projects", "v_col_month": "Month", "v_col_days": "Days left", "v_col_status": "Status",
        "v_data_table": "Data table", "v_need_js": "This chart needs JavaScript; the data table below has the same numbers.",
        "v_filter_customer": "Customer", "v_filter_all": "All", "v_not_in_snapshot": "Not in this snapshot.",
        "v_c_category": "Projects by category", "v_c_type": "Projects by type", "v_others_note": "Others: {names}",
        "v_col_category": "Category", "v_col_type": "Type",
        "v_lg_actual_planned": "Actual, same {n} planned projects", "v_c_fu": "FU RD: actual vs plan", "v_lg_fu_plan": "FU RD plan",
        "v_lg_fu_same": "FU RD actual, same projects", "v_lg_fu_all": "FU RD actual, all projects",
        "v_fu_note": "Plan covers {covered} / {total} projects, FU RD only. All {total} projects: {all} FTE in {mon}.",
        "v_fc_with": "With budget, {n} projects", "v_fc_without": "No budget, {n} projects", "v_fc_with_short": "With budget", "v_fc_without_short": "No budget",
        "v_fc_left": "{mon}: {used} of {cap} in use, {left} left", "v_fc_over": "{mon}: {used} of {cap} in use, {over} over", "v_fc_cap_label": "Headcount", "v_fc_cap_assumed": "{mon} headcount {n}, assumed unchanged", "v_fc_plan_label": "Plan", "v_fc_actual_label": "Actual", "v_fu_headline": "{mon}: {act} of {plan} planned, {pct}%",
        "v_c_composition": "Portfolio mix", "v_dim_stage": "Stage", "v_dim_category": "Category", "v_dim_type": "Type", "v_col_dim": "Dimension",
        "v_src_stage": "Briefing Stage column", "v_src_customer": "Briefing Customer column", "v_src_category": "Briefing Category column",
        "v_risk_head": "At risk ({n}):", "v_risk_note": "Milestone passed without a stage change, or MP slipped over {days} days. Slips the PM already confirmed are also listed under Data health.",
    },
    "zh": {
        "html_lang": "zh-Hant", "doc_title": "BU10 專案組合檢討 {ym}",
        "h1": "BU10 專案組合檢討",
        "intro": "每月一次。先看例外，再看依據。人力來自 EIS Control List，時程來自 PM 雙週 Briefing。",
        "tb_report": "報告月份", "tb_data": "人力資料", "tb_data_v": "{start} 至 {end}，{n} 案",
        "tb_snap": "Briefing 快照", "tb_snap_v": "{date}（第 {rev} 版）", "tb_gen": "產生", "tb_gen_v": "{date}，管線 v{ver}",
        "s_decisions": "本月要決定的事", "s_decisions_lead": "依急迫排序，每條附證據與出處。橘色只出現在這一節與需要決定的欄位。",
        "decision_needed": "要決定：", "source": "來源：", "none": "無",
        "ex_milestones_passed_title": "{n} 案里程碑已過期，Stage 沒有往前推",
        "ex_milestones_passed_ask": "請 PM 更新 Stage 或說明延後原因。",
        "ex_suspended_charging_title": "Briefing {briefed} 案中暫停 {suspended}，{charging} 案仍有人力掛帳，{twins} 案另有第二個代碼",
        "ex_suspended_charging_ask": "結案的案子不該再掛人力，決定剩餘 FTE 轉到哪；暫停的案子確認要重啟或結案；第二個代碼併回同一案。",
        "ex_susp_twin_h": "疑似同一案的第二個代碼",
        "ex_susp_twin_line": "{name}（{code}）在 Briefing 已{cat}，但 {twin}（{twin_code}）{mon} 仍掛 {fte} FTE{cl}",
        "ex_susp_twin_cl": "，且有自己的 Control List",
        "cat_terminated": "結案", "cat_suspended": "暫停", "cat_inactive": "停止",
        "ex_suspended_charging_legacy_title": "{n} 案非活躍（此快照早於結案/暫停分類），{charging} 案仍有人力掛帳，{twins} 案另有第二個代碼",
        "ex_suspended_charging_legacy_ask": "結案的案子不該再掛人力，決定剩餘 FTE 轉到哪；暫停的案子確認要重啟或結案；第二個代碼併回同一案。重新 ingest 此月即可取得結案/暫停分類。",
        "ex_susp_charging_h": "{mon} 仍掛帳",
        "ex_susp_wound_susp_h": "暫停中但 {since} 起已無人力：會重啟嗎？",
        "ex_susp_wound_line": "{name}：{peak_month} 高峰 {peak} FTE，{zero_since} 起為零",
        "ex_susp_zero_h": "暫停且全年無人力（{n}）",
        "ex_budget_missing_title": "{n} 份 Control List 未填 budget，Q4 預測只涵蓋 {covered} 案",
        "ex_budget_missing_ask": "要求 PM 補填，否則 Q4 產能討論沒有依據。",
        "ex_mp_slipped_title": "{n} 案 MP 較原訂延後超過 {days} 天",
        "ex_mp_slipped_ask": "確認新日期。",
        "ex_spare_capacity_title": "{n} 個部門負載低於 {pct}%，是僅存的可調度人力",
        "ex_spare_capacity_ask": "其餘 {full} 個部門已在 100%，填報機制看不到超載。",
        "src_briefing": "Briefing {date}", "src_briefing_summary": "Briefing Stage 欄；Resource Summary；Control List",
        "src_control_list_pva": "Control List「Plan vs. Actual」分頁", "src_briefing_mp": "Briefing MP Date 與 Original MP Date",
        "src_control_list_month": "Control List 月分頁，填入人力 ÷ 填報人數",
        "stage_rfq": "RFQ / RFI", "stage_poc": "POC", "stage_exec": "Execution", "stage_mp": "MP", "stage_sustain": "Sustain / EOP",
        "stage_terminated": "Terminated", "stage_suspended": "Suspended", "stage_fte": "{mon} 總人力 FTE（含 FU）",
        "s_upcoming": "未來 {weeks} 週的里程碑", "s_upcoming_lead": "含過去七天內已到期者。",
        "col_date": "日期", "col_project": "案子", "col_customer": "客戶", "col_milestone": "里程碑", "col_stage": "Stage",
        "passed": "已過",
        "s_timeline": "六個月時程", "s_timeline_lead": "週格線。只列里程碑落在視窗內，或 RFQ / RFI 尚無日期的案子；停案不列。",
        "no_dates": "{stage}，尚無日期", "legend_marks": "EVT（空方）  DVT（實方）  PVT（三角）  MP（圓）",
        "legend_late": "已過期未推進", "legend_today": "虛線 = 今天",
        "s_capacity": "人力與產能", "s_capacity_lead": "一張圖看三件事：BU 填報人數是天花板，實際人力已貼著它走，9 到 12 月的 budget 只涵蓋部分案子。",
        "cap_budget_note": "budget 涵蓋 {covered} / {total} 案，僅 BU RD + PM", "lg_capacity": "BU 填報人數（天花板）",
        "lg_capacity_note": "{mon} 之後沿用該月值",
        "lg_actual": "BU RD + PM 實際", "lg_budget": "BU RD + PM budget（虛線）", "lg_fu": "FU RD 實際",
        "lg_actual_planned": "BU RD + PM 實際，與 budget 同一批案子（細點線）",
        "lbl_ceiling": "天花板", "lbl_actual": "BU 實際", "lbl_budget": "Budget", "lbl_fu": "FU 實際",
        "lbl_actual_planned": "同 {n} 案實際",
        "s_health": "資料健康度", "s_health_lead": "每一項都影響上面圖表的可信度。「決定」要主管出面，「追蹤」由報表維護者處理。",
        "col_level": "層級", "col_check": "檢查項", "col_count": "案數", "col_projects": "影響的案子", "col_source": "來源",
        "lv_decide": "決定", "lv_track": "追蹤", "lv_ok": "正常",
        "hc_budget_missing": "Control List 未填 budget plan", "hc_milestones_passed": "里程碑已過但 Stage 未推進",
        "hc_suspended_second_identity": "停案另有第二個代碼在掛帳",
        "hc_in_briefing_no_cl": "在 Briefing（非結案或暫停）但沒有 Control List", "hc_in_cl_no_briefing": "有 Control List 但不在 Briefing",
        "hc_mp_slipped": "MP 較原訂延後超過 60 天", "hc_mp_typo": "MP 與原訂相差超過 300 天", "hc_customer_blank": "Customer 為 NA、TBD 或空白",
        "hc_name_unresolved": "名稱對不到 PROJECTCODE", "hc_task_description_blank": "BU-Task 有人力列但描述空白（月份）",
        "hc_briefing_stale": "Briefing 該列超過 60 天未更新", "hc_cl_unreadable": "Control List 檔案無法讀取",
        "hc_cl_format_drift": "Control List 缺分頁或缺欄", "hc_duplicate_source": "多筆來源列解析到同一專案代碼",
        "hc_dept_denominator_inconsistent": "填報人數跨檔不一致",
        "hc_dept_function_inconsistent": "部門 Function 跨檔不一致",
        "hc_cross_month_correction": "過去月份數字較上次報告有變", "hc_names_masked": "任務文字中被遮罩的人名",
        "hs_control_list": "Control List", "hs_briefing": "Briefing", "hs_cross": "交叉比對", "hs_snapshot": "上月快照",
        "s_appendix": "逐案附錄", "s_appendix_lead": "選一個案子。任務清單預設收合。",
        "ms_kickoff": "Kick-off", "ms_evt": "EVT", "ms_dvt": "DVT", "ms_pvt": "PVT", "ms_mp": "MP",
        "days_ahead": "{d} 天後", "days_ago": "{d} 天前", "not_filled": "未填", "not_in_briefing": "不在 Briefing",
        "pva_line": "budget {plan}{missing}，實際到 {mon} {actual}", "pva_missing": "（未填）",
        "no_control_list": "此案沒有 Control List。", "s_tasks": "任務清單",
        "task_summary": "{mon}：BU {bu} 項，FU {fu} 項，{fte} FTE", "col_side": "來源", "col_function": "Function", "col_dept": "部門", "col_fte": "FTE", "col_task": "任務",
        "expand": "展開", "collapse": "收合",
        "foot_1": "填報表單把每人 FTE 上限設在 1.0，超載不會出現在這些數字裡。",
        "foot_2": "部門負載的分母是填報人數，不是編制人數。",
        "foot_3": "凡用到 budget 的地方都標明涵蓋率。",
        "v_menu": "選單", "v_nav_overview": "總覽", "v_nav_decisions": "本月決策", "v_nav_health": "資料健康度", "v_nav_appendix": "各案附錄",
        "v_total": "合計", "v_kpi_total": "專案總數", "v_kpi_total_sub": "Briefing 內 {briefed} 案，結案或暫停 {inactive} 案",
        "v_kpi_rfq": "RFQ / RFI", "v_kpi_poc": "POC", "v_kpi_exec": "Execution", "v_kpi_mp": "MP + Sustain", "v_kpi_mp_sub": "MP {mp} 案，Sustain / EOP {sustain} 案",
        "v_kpi_risk": "風險", "v_kpi_risk_sub": "里程碑已過未轉階段，或 MP 延後超過 {days} 天",
        "v_c_stage": "各階段專案數", "v_c_customer": "各客戶專案數", "v_c_gantt": "未來 {months} 個月時程",
        "v_c_heat": "各 Function 負載", "v_c_heat_dept": "各部門負載", "v_c_forecast": "BU RD + PM：實際與填報人數",
        "v_c_milestones": "未來 {weeks} 週里程碑",
        "v_cat_not_in_briefing": "不在 Briefing", "v_cat_blank": "（空白）", "v_cat_others": "其他", "v_no_data": "無資料",
        "v_heat_note": "負載 = 分配 FTE ÷ 有填報的人數（不是編制）。灰格：無人填報。",
        "v_gantt_note": "紅色＝里程碑已過但階段未前進。結案與暫停的專案不列。",
        "v_today": "今天", "v_lg_cap": "BU 填報人數", "v_lg_cap_carried": "人數，假設維持 {mon}",
        "v_lg_actual": "實際，BU RD + PM", "v_lg_plan": "Budget，BU RD + PM", "v_lg_fu": "實際，FU RD",
        "v_lg_pva_actual": "實際", "v_lg_pva_plan": "計畫", "v_pva_no_plan": "這一組沒有 budget。",
        "v_st_passed": "已過", "v_st_due": "將到期", "v_st_ok": "未到期",
        "v_col_projects": "專案數", "v_col_month": "月份", "v_col_days": "剩餘天數", "v_col_status": "狀態",
        "v_data_table": "資料表", "v_need_js": "圖表需要 JavaScript；下方資料表有相同數字。",
        "v_filter_customer": "客戶", "v_filter_all": "全部", "v_not_in_snapshot": "這份快照沒有這項資料。",
        "v_c_category": "各類別專案數", "v_c_type": "各類型專案數", "v_others_note": "其他：{names}",
        "v_col_category": "類別", "v_col_type": "類型",
        "v_lg_actual_planned": "實際，同 {n} 個有 budget 的專案", "v_c_fu": "FU RD：實際與計畫", "v_lg_fu_plan": "FU RD 計畫",
        "v_lg_fu_same": "FU RD 實際，同一批專案", "v_lg_fu_all": "FU RD 實際，全部專案",
        "v_fu_note": "計畫涵蓋 {covered} / {total} 案，僅 FU RD。全部 {total} 案 {mon}：{all} FTE。",
        "v_fc_with": "有 budget，{n} 案", "v_fc_without": "沒有 budget，{n} 案", "v_fc_with_short": "有 budget", "v_fc_without_short": "沒有 budget",
        "v_fc_left": "{mon}：{cap} 人中已用 {used}，剩 {left}", "v_fc_over": "{mon}：{cap} 人中已用 {used}，超出 {over}", "v_fc_cap_label": "填報人數", "v_fc_cap_assumed": "{mon} 人數 {n}（假設不變）", "v_fc_plan_label": "計畫", "v_fc_actual_label": "實際", "v_fu_headline": "{mon}：計畫 {plan}，實際 {act}，{pct}%",
        "v_c_composition": "專案組合構成", "v_dim_stage": "階段", "v_dim_category": "類別", "v_dim_type": "類型", "v_col_dim": "維度",
        "v_src_stage": "Briefing Stage 欄", "v_src_customer": "Briefing Customer 欄", "v_src_category": "Briefing Category 欄",
        "v_risk_head": "風險（{n}）：", "v_risk_note": "里程碑已過未轉階段，或 MP 延後超過 {days} 天；PM 已確認的延後也列在資料健康度。",
    },
}


def t(lang: str, key: str, **kw) -> str:
    v = STRINGS[lang][key]          # 缺 key 直接 KeyError，不 fallback
    return v.format(**kw) if kw else v
